version: "3.9"

networks:
  simulacaocredito-net:

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simulacaocredito-net

  simulacaocredito-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulacaocredito-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - simulacaocredito-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - EVENTHUB_CONNECTION_STRING=${EVENTHUB_CONNECTION_STRING}
      - EVENTHUB_NAME=${EVENTHUB_NAME}