version: "3.9"

networks:
  simulacaocredito-net:

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: simulacaocredito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simulacaocredito-net

  simulacaocredito-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulacaocredito-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - simulacaocredito-net
