CREATE SEQUENCE simulacao_credito_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE resultado_simulacao_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE parcela_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE telemetria_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE SIMULACAO_CREDITO (
    ID_SIMULACAO BIGINT PRIMARY KEY DEFAULT nextval('simulacao_credito_seq'::regclass),
    CO_PRODUTO BIGINT NOT NULL,
    VALOR_DESEJADO NUMERIC(15,2) NOT NULL,
    PRAZO INTEGER NOT NULL,
    DATA_SIMULACAO DATE NOT NULL
);

CREATE TABLE RESULTADO_SIMULACAO (
    ID BIGINT PRIMARY KEY DEFAULT nextval('resultado_simulacao_seq'::regclass),
    SIMULACAO_ID BIGINT,
    TIPO VARCHAR(255) NOT NULL,
    VALOR_TOTAL_PARCELAS NUMERIC(15,2) NOT NULL,
    VALOR_MEDIO_PRESTACAO NUMERIC(15,2) NOT NULL,
    CONSTRAINT fk_simulacao
        FOREIGN KEY(SIMULACAO_ID)
        REFERENCES SIMULACAO_CREDITO(ID_SIMULACAO)
        ON DELETE CASCADE
);

CREATE TABLE PARCELA (
    ID BIGINT PRIMARY KEY DEFAULT nextval('parcela_seq'::regclass),
    RESULTADO_ID BIGINT,
    NUMERO INTEGER NOT NULL,
    VALOR_AMORTIZACAO NUMERIC(15,2) NOT NULL,
    VALOR_JUROS NUMERIC(15,2) NOT NULL,
    VALOR_PRESTACAO NUMERIC(15,2) NOT NULL,
    SALDO_DEVEDOR NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_resultado
        FOREIGN KEY(RESULTADO_ID)
        REFERENCES RESULTADO_SIMULACAO(ID)
        ON DELETE CASCADE
);

CREATE TABLE TELEMETRIA (
    ID BIGINT PRIMARY KEY DEFAULT nextval('telemetria_seq'::regclass),
    NOME_API VARCHAR(255) NOT NULL,
    TEMPO_RESPOSTA_MS BIGINT NOT NULL,
    STATUS INTEGER NOT NULL,
    DATA_REFERENCIA DATE NOT NULL
);
