CREATE TABLE PRODUTO (
    CO_PRODUTO BIGINT PRIMARY KEY,
    NO_PRODUTO VARCHAR(200) NOT NULL,
    PC_TAXA_JUROS NUMERIC(10, 9) NOT NULL,
    NU_MINIMO_MESES SMALLINT NOT NULL,
    NU_MAXIMO_MESES SMALLINT NULL,
    VR_MINIMO NUMERIC(18, 2) NOT NULL,
    VR_MAXIMO NUMERIC(18, 2) NULL
);

CREATE TABLE SIMULACAO_CREDITO (
    ID_SIMULACAO BIGSERIAL PRIMARY KEY,
    CO_PRODUTO BIGINT,
    VALOR_DESEJADO NUMERIC(15,2) NOT NULL,
    PRAZO INTEGER NOT NULL,
    DATA_SIMULACAO DATE NOT NULL,
    CONSTRAINT fk_produto
        FOREIGN KEY (CO_PRODUTO)
        REFERENCES PRODUTO(CO_PRODUTO)
);

CREATE TABLE RESULTADO_SIMULACAO (
    ID BIGSERIAL PRIMARY KEY,
    SIMULACAO_ID BIGINT,
    TIPO VARCHAR(255) NOT NULL,
    VALOR_TOTAL_PARCELAS NUMERIC(15,2) NOT NULL,
    VALOR_MEDIO_PRESTACAO NUMERIC(15,2) NOT NULL,
    CONSTRAINT fk_simulacao
        FOREIGN KEY(SIMULACAO_ID)
        REFERENCES SIMULACAO_CREDITO(ID_SIMULACAO)
        ON DELETE CASCADE
);

CREATE TABLE PARCELA (
    ID BIGSERIAL PRIMARY KEY,
    RESULTADO_ID BIGINT,
    NUMERO INTEGER NOT NULL,
    VALOR_AMORTIZACAO NUMERIC(15,2) NOT NULL,
    VALOR_JUROS NUMERIC(15,2) NOT NULL,
    VALOR_PRESTACAO NUMERIC(15,2) NOT NULL,
    SALDO_DEVEDOR NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_resultado
        FOREIGN KEY(RESULTADO_ID)
        REFERENCES RESULTADO_SIMULACAO(ID)
        ON DELETE CASCADE
);

CREATE TABLE TELEMETRIA (
    ID BIGSERIAL PRIMARY KEY,
    NOME_API VARCHAR(255) NOT NULL,
    TEMPO_RESPOSTA_MS BIGINT NOT NULL,
    STATUS INTEGER NOT NULL,
    DATA_REFERENCIA DATE NOT NULL
);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (1, 'Produto 1', 0.017900000, 0, 24, 200.00, 10000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (2, 'Produto 2', 0.017500000, 25, 48, 10001.00, 100000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (3, 'Produto 3', 0.018200000, 49, 96, 100000.01, 1000000.00);

INSERT INTO PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES (4, 'Produto 4', 0.015100000, 96, NULL, 1000000.01, NULL);
