CREATE TABLE SIMULACAO_CREDITO (
    ID_SIMULACAO BIGSERIAL PRIMARY KEY,
    CO_PRODUTO BIGINT,  -- Mantém a coluna, mas sem FK
    VALOR_DESEJADO NUMERIC(15,2) NOT NULL,
    PRAZO INTEGER NOT NULL,
    DATA_SIMULACAO DATE NOT NULL
);

CREATE TABLE RESULTADO_SIMULACAO (
    ID BIGSERIAL PRIMARY KEY,
    SIMULACAO_ID BIGINT,
    TIPO VARCHAR(255) NOT NULL,
    VALOR_TOTAL_PARCELAS NUMERIC(15,2) NOT NULL,
    VALOR_MEDIO_PRESTACAO NUMERIC(15,2) NOT NULL,
    CONSTRAINT fk_simulacao
        FOREIGN KEY(SIMULACAO_ID)
        REFERENCES SIMULACAO_CREDITO(ID_SIMULACAO)
        ON DELETE CASCADE
);

CREATE TABLE PARCELA (
    ID BIGSERIAL PRIMARY KEY,
    RESULTADO_ID BIGINT,
    NUMERO INTEGER NOT NULL,
    VALOR_AMORTIZACAO NUMERIC(15,2) NOT NULL,
    VALOR_JUROS NUMERIC(15,2) NOT NULL,
    VALOR_PRESTACAO NUMERIC(15,2) NOT NULL,
    SALDO_DEVEDOR NUMERIC(38,2) NOT NULL,
    CONSTRAINT fk_resultado
        FOREIGN KEY(RESULTADO_ID)
        REFERENCES RESULTADO_SIMULACAO(ID)
        ON DELETE CASCADE
);

CREATE TABLE TELEMETRIA (
    ID BIGSERIAL PRIMARY KEY,
    NOME_API VARCHAR(255) NOT NULL,
    TEMPO_RESPOSTA_MS BIGINT NOT NULL,
    STATUS INTEGER NOT NULL,
    DATA_REFERENCIA DATE NOT NULL
);
